{block content}

<div class="box">
{control clip 'homepage'}
</div>

<div class="span-9">


<div class="box graybox newest-articles">
	<h3>Nejnovější články</h3>

	{control newestArticles $newestArticles}
</div>

</div>


<div class="span-9 last">

<div class="box">
	{control clip 'supportUs'}
</div>

<div class="box">
	<h3>Facebook</h3>
	<fb:like-box href="http://www.facebook.com/pages/Kladno-minule/218245624350" width="310" show_faces="true" stream="true" header="false"></fb:like-box>
</div>
</div>