{block content}

<div class="box">
<h1>{$title} - {$current}/{$total}</h1>

<p class="photo-detail">
<a href="{if $photo->nextPhoto}{link photos id => $page->id, gallery => $gallery->id, photo => $photo->nextPhoto->id}{else}{link default $page->id}{/if}">
	{$photo|imagepath|thumbnail:670:500|imagehtml}
</a>
</p>

<p n:if="$photo->description" class="photo-description">{$photo->description}</p>

<p style="margin-top:2em"><fb:like show_faces="false" font="trebuchet ms" href="{link //this}"></fb:like></p>

{if $photo->lat && $photo->lng}
<h2>Mapa</h2>
<div id="pagemap" style="height:300px;"></div>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">
var point = new google.maps.LatLng({$photo->lat}, {$photo->lng});
var map = new google.maps.Map(document.getElementById("pagemap"), {
	zoom: 13,
	center: point,
	mapTypeId: google.maps.MapTypeId.ROADMAP
});

marker = new google.maps.Marker({
	map: map,
	position: point
});
</script>
{/if}

</div>

<div class="box graybox comments">
<h2>Komentáře</h2>

{control comments}
</div>

{/block}

{block sidebar}
<div class="box graybox">
	<h3>Fotogalerie</h3>

	<p class="gallery-prev-next clearfix">
		<a class="prev" n:href="photos id => $page->id, gallery => $gallery->id, photo => $photo->prevPhoto->id" n:if="$photo->prevPhoto">
			{$photo->prevPhoto|imagepath|thumbnail:80:80:'crop'|imagehtml}
			Předchozí
		</a>
		<a class="next" n:href="photos id => $page->id, gallery => $gallery->id, photo => $photo->nextPhoto->id" n:if="$photo->nextPhoto">
			{$photo->nextPhoto|imagepath|thumbnail:80:80:'crop'|imagehtml}
			Další
		</a>
	</p>

	<ul>
		<li><a n:href="default $page->id">Zpět na článek</a></li>
	</ul>
</div>

{include #parent}
{/block}