{form $form}

<fieldset>
	<div class="error" n:foreach="$formErrors as $error">{$error}</div>

	<p>
		{label name}Vaše jméno{/label}<br>
		{input name}
	</p>
	<p>
		{label mail}Váš e-mail{/label}<br>
		{input mail}
	</p>
	<p>
		{label password}Heslo{/label}<br>
		{input password}
	</p>
	<p>
		{label password2}Vaše nové heslo ještě jedno pro kontrolu{/label}<br>
		{input password2}
	</p>

	<p>{input s value => "Registrujte se"}</p>
</fieldset>

{/form}