<ul class="article-list clearfix">
	<li n:foreach="$articles as $article" n:class="$iterator->odd ? 'odd' : 'even', count($article->photogalleries) === 0 ? 'without-thumbnail'">
		{$article|pagethumbnail}
		<h4><a href="{plink Page: $article->id}">{$article->name}</a></h4>
		<p>{$article->description}</p>
		<p class="detail">
			Datum: {$article->created|date:'j.n.Y'}{if $showAuthor && $article->author},
			autor: <a href="{plink User:profile $article->author->id}">{$article->author->name}</a>{/if}{if $showCategory && $article->category},
			kategorie: <a href="{plink Category: $article->category->id}">{$article->category->name}</a>{/if}
		</p>
	</li>
</ul>

{if $showPaginator}
{control paginator}
{/if}